# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v4.0.5
      #with:
        # GitHub token
        #token: # default is ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        #timeout: # optional, default is 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        #error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        #reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        #artifact_name: # optional, default is github-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        #preview: # optional, default is false
          
